name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      id: version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      id: build
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t briian0024/nuevorest:$NEW_VERSION .
        docker build -t briian0024/nuevorest:latest .

    - name: Push Docker Image
      env:
        DOCKER_IMAGE_VERSION: ${{ steps.build.outputs.version }}
      run: |
        docker push briian0024/nuevorest:${DOCKER_IMAGE_VERSION}
        docker push briian0024/nuevorest:latest
