on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
  
 
      NEW_VERSION: <version_number>
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
    
      run: |
        docker buildx build .
        --file Dockerfile
        --tag "briian0024/nuevorest:${{ env.NEW_VERSION }}"
        --platform linux/amd64

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push "briian0024/nuevorest:${{ env.NEW_VERSION }}"

      